# Builds the sound-effects library from Karl's folders: python3 sfx_build.py <source folder> [<more folders> …] <library/sound>
# Runs the measurements (sfx_index.py), files every sound under its category from categories.json,
# trims it to start 5 ms before it sounds (so its sync point is a known, small offset) and to end 80 ms
# after it falls 40 dB, writes 48 kHz WAV, and writes sfx/index.json and catalogue.md with times relative
# to the trimmed file. Needs ffmpeg and the sfx_index.py requirements.
import json, os, subprocess, sys
srcs, lib = sys.argv[1:-1], sys.argv[-1]
here = os.path.dirname(os.path.abspath(__file__))
items = []
for n, src in enumerate(srcs):
    tmp = os.path.join(lib, "_measure"); os.makedirs(tmp, exist_ok=True)
    subprocess.run([sys.executable, os.path.join(here, "sfx_index.py"), src, tmp], check=True)
    for it in json.load(open(os.path.join(tmp, "index.json"))):
        it["src"] = src; items.append(it)
    import shutil; shutil.rmtree(tmp)
cats = json.load(open(os.path.join(lib, "categories.json")))
out = []
for it in items:
    cat, character, licence = cats["sounds"][it["id"]]
    start = max(0.0, it["onset"] - 0.005); end = min(it["duration"], it["end"] + 0.08)
    rel = os.path.join("sfx", cat, it["id"] + ".wav")
    os.makedirs(os.path.join(lib, "sfx", cat), exist_ok=True)
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-ss", f"{start:.3f}", "-t", f"{end - start:.3f}", "-i", os.path.join(it["src"], it["file"]),
                    "-af", "afade=t=out:st=%.3f:d=0.04" % max(0, end - start - 0.04), "-ar", "48000", "-c:a", "pcm_s16le", os.path.join(lib, rel)], check=True)
    sh = lambda v: round(v - start, 3)
    # swells, swipes, whooshes and risers land at their loudest point; everything else on its first strong transient
    sync = it["hit"] if cat in ("swipe", "whoosh", "riser") else it["sync"]
    out.append({"id": it["id"], "file": rel, "category": cat, "character": character, "licence": licence, "sync": sh(sync),
                "transients": [sh(t) for t in it["transients"]], "length": round(end - start, 3), "decay": it["decay"], "lufs": it["lufs"],
                "brightness_hz": it["brightness_hz"], "pitch_move_semitones": it["pitch_move_semitones"], "hits": it["hits"], "original": it["sources"]})
json.dump(out, open(os.path.join(lib, "sfx", "index.json"), "w"), indent=1)
# a readable catalogue
lines = ["# Sound-effects catalogue", "", "Generated by `scripts/sfx_build.py` from Karl's folder. `sync` is when the sound lands, in seconds",
         "from the start of the trimmed file: place the file that much before the picture's event. Loudness",
         "varies widely; the mixer (`scripts/sound_mix.py`) sets every sound to its role's level. Licence `karl`:",
         "Karl's own motion-design pack, supplied by him for client films. Licence `cc0`: Kenney's Interface Sounds",
         "(kenney.nl), public domain. Licence `apple`:",
         "Apple's own system sounds, for reference and internal drafts only, never in a client delivery; their files stay in Karl's repository and are not published with the library.", ""]
for cat, what in cats["categories"].items():
    rows = [o for o in out if o["category"] == cat]
    if not rows: continue
    lines += [f"## {cat}", "", what, "", "| id | character | sync s | length s | hits | pitch | licence |", "|---|---|---|---|---|---|---|"]
    for o in sorted(rows, key=lambda o: (o["licence"] != "pixabay", o["length"])):
        lines.append(f"| `{o['id']}` | {o['character']} | {o['sync']:.3f} | {o['length']:.2f} | {o['hits']} | {o['pitch_move_semitones']:+.0f} st | {o['licence']} |")
    lines.append("")
open(os.path.join(lib, "catalogue.md"), "w").write("\n".join(lines))
# the generated sounds (whooshes, risers, impacts) are added by sfx_synth.py; run it after this
print(f"{len(out)} sounds filed in {lib}/sfx/<category>/, index.json and catalogue.md written")
